# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFiT483EBrMSW7SuLbz6TZF7crrcQPMz
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

st.set_page_config(
    page_title="Inventory Shrinkage Dashboard",
    layout="wide"
)

st.title("📦 Inventory Shrinkage Analytics & Prediction")

@st.cache_data
def load_data():
    return pd.read_csv("lp_shrinkage_project_data.csv")

df = load_data()
df["date"] = pd.to_datetime(df["date"])

# ======================
# SIDEBAR FILTER
# ======================
st.sidebar.header("🔍 Filter Data")

store = st.sidebar.selectbox(
    "Select Store",
    ["All"] + sorted(df["store_id"].unique())
)

department = st.sidebar.selectbox(
    "Select Department",
    ["All"] + sorted(df["department"].unique())
)

filtered_df = df.copy()
if store != "All":
    filtered_df = filtered_df[filtered_df["store_id"] == store]
if department != "All":
    filtered_df = filtered_df[filtered_df["department"] == department]

# ======================
# KPI
# ======================
st.subheader("📊 Key Metrics")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Records", len(filtered_df))
col2.metric("Avg Shrinkage", f"{filtered_df['shrinkage'].mean():.2f}")
col3.metric("Total Sales", f"{filtered_df['sales'].sum():,}")
col4.metric("Avg Inventory", f"{filtered_df['inventory'].mean():.0f}")

# ======================
# VISUALIZATION
# ======================
st.subheader("📈 Data Visualization")

colA, colB = st.columns(2)

with colA:
    fig, ax = plt.subplots()
    ax.hist(filtered_df["shrinkage"], bins=20)
    ax.set_title("Shrinkage Distribution")
    st.pyplot(fig)

with colB:
    dept_avg = filtered_df.groupby("department")["shrinkage"].mean()
    fig, ax = plt.subplots()
    dept_avg.plot(kind="bar", ax=ax)
    ax.set_title("Avg Shrinkage by Department")
    st.pyplot(fig)

# ======================
# MODEL
# ======================
st.subheader("🤖 Shrinkage Prediction")

features = ["sales", "returns", "inventory", "promo", "staff_on_duty"]
X = df[features]
y = df["shrinkage"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_test)

mae = mean_absolute_error(y_test, preds)
st.info(f"Model MAE: {mae:.2f}")

# ======================
# PREDICTION INPUT
# ======================
st.subheader("🧪 Try Prediction")

c1, c2, c3 = st.columns(3)
sales = c1.number_input("Sales", min_value=0)
returns = c2.number_input("Returns", min_value=0)
inventory = c3.number_input("Inventory", min_value=0)

promo = st.selectbox("Promo Active?", [0, 1])
staff = st.slider("Staff on Duty", 1, 20, 5)

if st.button("Predict Shrinkage"):
    result = model.predict([[sales, returns, inventory, promo, staff]])[0]
    st.success(f"Predicted Shrinkage: {result:.0f}")

    if result > df["shrinkage"].mean():
        st.warning("⚠️ High Risk Shrinkage")
    else:
        st.info("✅ Shrinkage Level Normal")